mongo:
  name: reactive

spring:
  application:
    name: reactiveshop
  profiles: prod
  data:
    mongodb:
      uri: mongodb://localhost:27017/reactive
      database: reactive

currency:
  api:
    url: http://data.fixer.io/api/convert
    key: #provide here your api key
    enabled: true
